export const paintingData = [
  // Front Wall
{
  imgSrc: `artworks/27.jpg`,
  width: 5,
  height: 3,
  position: { x: -15, y: 2, z: -19.5 },
  rotationY: 0,
  info: {
    title: `QiQi x Biển Cam Ranh`,
    artist: 'LeVietHaiQuan',
    description: `Biển Cam Ranh đẹp quá`,
    year: `2025`,
    link: 'https://www.facebook.com/imagoodsupport',
  },
},
{
  imgSrc: `artworks/2.jpg`,
  width: 5,
  height: 3,
  position: { x: -5, y: 2, z: -19.5 },
  rotationY: 0,
  info: {
    title: `N.I.M`,
    artist: 'Như Quỳnh',
    description: `Như Quỳnh chụp đẹp quá`,
    year: `2023`,
    link: 'https://www.facebook.com/imagoodsupport',
  },
},
{
  imgSrc: `artworks/3.jpg`,
  width: 5,
  height: 3,
  position: { x: 5, y: 2, z: -19.5 },
  rotationY: 0,
  info: {
    title: `Đoàn - Hội CNTT OU`,
    artist: 'N.I.M PhotoClub',
    description:'Hành trình về nguồn tại đạo Gạc Ma',
    year: `2025`,
    link: 'https://www.facebook.com/imagoodsupport',
  },
},
{
  imgSrc: `artworks/23.jpg`,
  width: 5,
  height: 3,
  position: { x: 15, y: 2, z: -19.5 },
  rotationY: 0,
  info: {
    title: `Dốc Lết - Ninh Hoà`,
    artist: 'LeVietHaiQuan',
    description: `Dốc Lết đẹp quá`,
    year: `2025`,
    link: 'https://www.facebook.com/imagoodsupport',
  },
},

  // Back Wall
  ...[
  {
    imgSrc: `artworks/5.jpg`,
    width: 5,
    height: 3,
    position: { x: -15, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: `QiQi x Biển Cam Ranh`,
      artist: 'LeVietHaiQuan',
      description: `Biển Cam Ranh đẹp quá`,
      year: `2025`,
      link: 'https://www.facebook.com/imagoodsupport',
    },
  },
  {
    imgSrc: `artworks/6.jpg`,
    width: 5,
    height: 3,
    position: { x: -5, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: `QiQi x Đồng Cỏ`,
      artist: 'LeVietHaiQuan',
      description:' Đồng Cỏ đẹp quá',
      year: `2025`,
      link: 'https://www.facebook.com/imagoodsupport',
    },
  },
  {
    imgSrc: `artworks/7.jpg`,
    width: 5,
    height: 3,
    position: { x: 5, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: `OU Help To Be Helped Club`,
    artist: 'CLB Hỗ trợ người nước ngoài học tập tại trường Đại học Mở TP.HCM', // <-- dùng lại key 'artist'
    year: `2025`,
    description: `Founded on Sept 20, 2024, the club supports international students at OU with extracurricular activities and mental well-being.`,
    link: 'https://www.facebook.com/imagoodsupport',
    },
  },
  {
    imgSrc: `artworks/8.jpg`,
    width: 5,
    height: 3,
    position: { x: 15, y: 2, z: 19.5 },
    rotationY: Math.PI,
    info: {
      title: `LeVietHaiQuan`,
      artist: 'LeVietHaiQuan',
      description: `LeVietHaiQuan chụp đẹp quá`,
      year: `2025`,
      link: 'https://www.facebook.com/imagoodsupport',
    },
  }
],
// Left Wall
...[
  {
    imgSrc: `artworks/9.jpg`,
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: -15 },
    rotationY: Math.PI / 2,
    info: {
      title: `Tuyết Trinh x Đồng Cỏ`,
      artist: 'LeVietHaiQuan',
      description: `Hải Quân chụp đẹp quá`,
      year: `2025`,
      link: 'https://www.facebook.com/imagoodsupport',
    },
  },
  {
    imgSrc: `artworks/10.jpg`,
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: -5 },
    rotationY: Math.PI / 2,
    info: {
      title: `LeVietHaiQuan`,
      artist: 'LeVietHaiQuan',
      description: `LeVietHaiQuan chụp đẹp quá`,
      year: `2025`,
      link: 'https://www.facebook.com/imagoodsupport',
    },
  },
  {
    imgSrc: `artworks/11.jpg`,
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: 5 },
    rotationY: Math.PI / 2,
    info: {
      title: `LeVietHaiQuan`,
      artist: 'LeVietHaiQuan',
      description: `LeVietHaiQuan chụp đẹp quá`,
      year: `2025`,
      link: 'https://www.facebook.com/imagoodsupport',  
    },
  },
  {
    imgSrc: `artworks/12.jpg`,
    width: 5,
    height: 3,
    position: { x: -19.5, y: 2, z: 15 },
    rotationY: Math.PI / 2,
    info: {
      title: `LeVietHaiQuan`,
      artist: 'LeVietHaiQuan',
      description: `LeVietHaiQuan chụp đẹp quá`,
      year: `2025`,
      link: 'https://www.facebook.com/imagoodsupport',
    },
  },
  ],
// Right Wall
  ...[
    {
    imgSrc: `artworks/13.jpg`,
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: -15 },
    rotationY: -Math.PI / 2,
    info: {
      title: `LeVietHaiQuan`,
      artist: 'LeVietHaiQuan',
      description: `LeVietHaiQuan chụp đẹp quá`,
      year: `2025`,
      link: 'https://www.facebook.com/imagoodsupport',
    },
  },
  {
    imgSrc: `artworks/14.jpg`,
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: -5 },
    rotationY: -Math.PI / 2,
    info: {
      title: `LeVietHaiQuan`,
      artist: 'LeVietHaiQuan',
      description: `LeVietHaiQuan chụp đẹp quá`,
      year: `2025`,
      link: 'https://www.facebook.com/imagoodsupport',
    },
  },
  {
    imgSrc: `artworks/15.JPG`,
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: 5 },
    rotationY: -Math.PI / 2,
    info: {
      title: `LeVietHaiQuan`,
      artist: 'LeVietHaiQuan',
      description: `LeVietHaiQuan chụp đẹp quá`,
      year: `2025`,
      link: 'https://www.facebook.com/imagoodsupport',
    },
  },
  {
    imgSrc: `artworks/16.JPG`,
    width: 5,
    height: 3,
    position: { x: 19.5, y: 2, z: 15 },
    rotationY: -Math.PI / 2,
    info: {
      title: `LeVietHaiQuan`,
      artist: 'LeVietHaiQuan',
      description: `LeVietHaiQuan chụp đẹp quá`,
      year: `2025`,
      link: 'https://www.facebook.com/imagoodsupport',
    },
  },
  ],
];
